project:
  type: book

book:
  title: "spicyWorkBook"
  author: "Alex Qin"
  date: "11/11/2024"
  chapters:
    - index.qmd
    - 01-overview.qmd
    - 02-processing.qmd
    - 03-quality_control.qmd
    - 04-cell_annotation.qmd
    - 05-cell_localisation.qmd
    - 06-cellular_niches.qmd
    - 07-changes_in_marker_expression.qmd 
    - 08-classification.qmd
    - 09-references.qmd
  navbar:
    logo: images/USydLogo.svg

bibliography: references.bib

format:
  html:
    theme: [cosmo, styles.scss]
    css: styles.css
    toc: true
  pdf:
    documentclass: scrreprt

editor: visual

