project:
  type: book
  output-dir: docs

book:
  title: "spicyPlayBook"
  author: "Alex Qin"
  date: "11/11/2024"
  chapters:
    - index.qmd
    - 01-processing.qmd
    - 02-quality_control.qmd
    - 03-cell_annotation.qmd
    - 04-cell_localisation.qmd
    - 05-cellular_niches.qmd
    - 06-changes_in_marker_expression.qmd 
    - 07-classification.qmd
    - 08-case_study1.qmd
    - 09-references.qmd
  navbar:
    logo: images/USydLogo.svg

bibliography: references.bib

format:
  html:
    theme: [cosmo, styles.scss]
    css: styles.css
    toc: true
  pdf:
    documentclass: scrreprt

editor: visual

