project:
  type: book

book:
  title: "spicyWorkBook"
  author: "Norah Jones"
  date: "11/11/2024"
  chapters:
    - index.qmd
    - 01-overview.qmd
    - 02-processing.qmd
    - 03-quality_control.qmd
    - 04-cell_annotation.qmd
    - 05-condition_analysis.qmd
    - 06-survival_analysis.qmd
    - 07-classification.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

